# download helm
- name: "download helm"
  shell: "curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3"

# set permissions
- name: "set permissions"
  shell: "chmod 700 get_helm.sh"

# install helm
- name: "install helm"
  shell: "./get_helm.sh"
