# download helm
- name: "download helm"
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    mode: 700
    dest: "/tmp/get_helm.sh"

# install helm
- name: "install helm"
  become: yes
  shell: "/tmp/get_helm.sh"
