# install fluxctl
- name: install fluxctl
  become: yes
  shell: snap install fluxctl --classic

# add fluxcd repo
- name: add fluxcd repo
  become: yes
  shell: helm repo add fluxcd https://charts.fluxcd.io


# add crds
- name: add crds
  become: yes
  shell: kubectl apply -f https://raw.githubusercontent.com/fluxcd/helm-operator/master/deploy/crds.yaml

# - create the flux namespace
- name: create ns flux
  become: yes
  shell: kubectl create namespace flux

# copy ssh key for git access
- name: copy ssh key for git access
  become: yes
  copy:
    src: flux-git-deploy
    dest: .kube/flux-git-deploy
    mode: 400 

# add secret for flux to use
- name: add secret for flux to use
  become: yes
  shell: kubectl -n flux create secret generic flux-git-deploy --from-file=identity=/home/ubuntu/.kube/flux-git-deploy

  # - install flux
- name: install flux
  become: yes
  shell: helm upgrade -i flux --set git.url=git@github.com:{{ ghuser }}/{{ repo_name }} --set git.branch={{ git_branch }} --set git.path="releases\,namespaces" --set git.secretName=flux-git-deploy --namespace flux fluxcd/flux

  # - install helm operator
- name: install helm operator
  become: yes
  shell: helm upgrade -i helm-operator --set git.ssh.secretName={{ secret_name }} --namespace flux fluxcd/helm-operator --set helm.versions=v3

# wait for flux to be deployed
- name: wait for pods to come up
  shell: kubectl get pods -n flux -o json
  retries: 5
  delay: 20
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]

# write the identity key to file
- name: print key
  become: yes
  shell: fluxctl identity --k8s-fwd-ns flux
  register: output

- name: copy key to file
  copy:
    content: "{{ output.stdout }}"
    dest: "~/{{ secret_name }}.txt"
