apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator
  labels:
    app: prometheus-operator
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: prometheus-operator