apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    helmVersion: v3
    repository: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: 12.8.1
    forceUpgrade: true
  values:
    grafana:
      service:
        type: NodePort
    prometheus:
      service:
        type: NodePort
