apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: default-podinfo
  labels:
    app.kubernetes.io/name: default-podinfo
    release: monitoring-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: default-podinfo
      release: monitoring-kube-prometheus-stack
  endpoints:
  - path: /metrics
    port: http
    interval: 15s
