clusterName: "elasticsearch"
nodeGroup: "master"

masterService: "elasticsearch-master"

roles:
  master: "true"
  ingest: "true"
  data: "true"

replicas: 3
minimumMasterNodes: 2

# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

# Shrink default JVM heap.
esJavaOpts: "-Xmx128m -Xms128m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"

networkHost: "0.0.0.0"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 100M

protocol: http
httpPort: 9200
transportPort: 9300

## Enabling this will publically expose your Elasticsearch instance.
## Only enable this if you have security enabled on your cluster
#ingress:
#  enabled: false
#  annotations: {}
#  path: /
#  hosts:
#    - chart-example.local
#  tls: []