- name: Create kube-state-metrics directory
  file: path=kubernetes/kube-state-metrics state=directory mode=0755

- name: prepare kube-state-metrics
  copy:
    src: kube-state-metrics
    dest: kubernetes

- name: Deploy kube-state-metrics
  command: "kubectl apply -f kubernetes/kube-state-metrics"