- name: Create prometheus-operator directory
  file: path=kubernetes/prometheus-operator state=directory mode=0755

- name: prepare prometheus-operator
  copy:
    src: prometheus-operator
    dest: kubernetes

- name: Deploy prometheus-operator
  command: kubectl apply -f kubernetes/prometheus-operator

- name: Wait until service monitor is available
  command: kubectl get servicemonitor 
  register: servicemonitor_result
  until: servicemonitor_result.rc == 0
  retries: 20
  delay: 10
  ignore_errors: yes

- name: Wait until service monitor is available
  command: kubectl get prometheus
  register: prometheus_result
  until: prometheus_result.rc == 0
  retries: 20
  delay: 10