# - install flux
#- name: sudo install flux
#  become: yes
#  shell: sudo snap install fluxctl

# - create the flux namespace
- name: create ns flux
#  become: yes
  shell: kubectl create namespace flux

# - connect to your repo
- name: connect repo
#  become: yes
  ghuser: slnxc
  shell: "fluxctl install --git-user={{ ghuser }} --git-email={{ ghuser }}@users.noreply.github.com --git-url=git@github.com:{{ ghuser }}/k8s-reference-design --git-path=releases --git-branch=monitoring --namespace=flux | kubectl apply -f -"